### ISSUE TITLE
jobs.ls-router.networks.default.static_ips.0`: `$.jobs.ls-router.networks.default.static_ips

### ISSUE THREAD

**Issue by mrdavidlaing** [pivotal-cf/logsearch-for-cloudfoundry-operators-boshrelease#1]
```
Hi Derik and David,

Thanks so much for your help in the cross-team pairing session we had the other day. We've been continuing to work with logsearch, and we've run into a little problem.

We're trying to generate a new manifest that uses the template from logsearch-for-cloudfoundry-operators-boshrelease. When we try to generate the manifest using generate_deployment_manifest, we find that an error occurs merging the templates:

"Unable to resolve `jobs.ls-router.networks.default.static_ips.0`: `$.jobs.ls-router.networks.default.static_ips` could not be found in the YAML datastructure

Any advice on what to do about this?

Thanks so much,

Nolan && Yuan
```

**Comment by mrdavidlaing** [comment]
Bug created - https://www.pivotaltracker.com/story/show/118633451

**Comment by ablease** [comment]
Hi, 

We couldn't reproduce this error when creating a manifest from the [aws-example-stub](https://github.com/logsearch/logsearch-boshrelease/blob/develop/templates/stub.aws.example.yml) in logsearch-boshrelease, and then merging that manifest with the [example-with-basic-auth](https://github.com/pivotal-cf/logsearch-for-cloudfoundry-operators-boshrelease/blob/master/templates/example-with-basic-auth.yml) in the operators release. 

However we did recreate this problem when trying to use the [example-with-basic-auth](https://github.com/pivotal-cf/logsearch-for-cloudfoundry-operators-boshrelease/blob/master/templates/example-with-basic-auth.yml) as a stub with the logsearch-boshrelease generate_manifest script directly. 

Just to clarify you cannot use the template from logsearch-for-cloudfoundry-operators-boshrelease to generate a manifest using the logsearch-boshrelease generate script. 

It could be an iaas specific issue. Which iaas are you trying to generate a manifest for?

**Comment by yuanzhao** [comment]
Sorry, we use it in a wrong way.

 Following is how we use it:
`./scripts/generate_deployment_manifest aws ~/workspace/logsearch-for-cloudfoundry-operators-boshrelease/templates/example-with-basic-auth.yml  templates/stub.aws.example.yml > ~/a.yml`

And we got the error message:
`1 error(s) detected:
$.jobs.11.properties.syslog.host: Unable to resolve 'jobs.ls-router.networks.default.static_ips.0': '$.jobs.ls-router.networks' could not be found in the YAML datastructure`

May be we need to write another deployment template file. 
Would you mind to share how you generate the manifest and merge it with  example-with-basic-auth in the operators release? Thanks!

**Comment by kirederik** [comment]
@yuanzhao 

To generate the manifest with the logsearch-for-cloudfoundry-operators release, you need:
1. Generate the base manifest using logsearch-boshrelease stubs

```
bash$> cd logsearch-boshrelease
$> ./scripts/generate_deployment_manifest aws templates/stub.aws.example.yml > /tmp/logsearch.yml
```
1. Generate the final manifest with logsearch-for-cloudfoundry-operators

``` bash
$> cd logsearch-for-cloudfoundry-operators
$> ./scripts/generate_deployment_manifest /tmp/logsearch.yml templates/example-with-basic-auth.yml
```

You can find more information [here](https://github.com/pivotal-cf/logsearch-for-cloudfoundry-operators-boshrelease/blob/master/README.md).

Please let us know if this solve the issue.
